Lagouwh/App/urls.py
from django.conf.urls import url

from App import views

urlpatterns=[
    #主页
    url(r'^$',views.index,name='index'),
    #更多职位
    url(r'^list/$',views.list,name='list'),
    # #筛选职位表
    url(r'^shailist/(?P<payfor>\d{0,})/(?P<exp>\d{0,})/(?P<degree>\d{0,})/(?P<worktype>\d{0,})/(?P<area>\d{0,})/$',views.shailist,name='shailist'),
    #搜索职位表
    url(r'^seeklist/(?P<spid>\d+)/$',views.seeklist,name='seeklist'),
    # 公司列表
    # url(r'^companylist/$',views.companylist,name='companylist'),
    #点击职位后详情，未登录状态
    url(r'^postdetail/$',views.postdetail,name='postdetail'),
    #公司详情
    url(r'^myhome/$',views.myhome,name='myhome'),
    #账号设置
    url(r'^accountbind/$',views.accountbind,name='accountbind'),
    #修改密码
    url(r'updatepwd/$',views.updatepwd,name='updatepwd'),
    #职位订阅
    url(r'^subscribe/$',views.subscribe,name='subscribe'),
    #我的简历
    url(r'^jianli/$',views.jianli,name='jianli'),
    #简历投递状态
    url(r'^delivery/$',views.delivery,name='delivery'),
    #简历推荐岗位
    url(r'^mylist/$',views.mylist,name='mylist'),
    #联系我们
    url(r'^about/$',views.about,name='about'),
    #用户登录
    url(r'^login/$',views.login,name='login'),
    #用户注册
    url(r'^register/$',views.register,name='register'),
    #用户退出登录
    url(r'^logout/$',views.logout,name='logout'),
    #公司申请第一步11111111111111111111111111
    url(r'^companyapplyfirst/$',views.companyapplyfirst,name='comfirst'),
    #公司申请第二部22222222222222222222222222
    url(r'^companyapplysecond/$',views.companyapplysecond,name='comsecond'),
    #公司申请第三部33333333333333333333333333
    url(r'^companyapplythird/$',views.companyapplythird,name='comthird'),
    #公司申请第四部44444444444444444444444444
    url(r'^companyapplyfourth/$', views.companyapplyfourth, name='comfourth'),
    #公司申请第五部55555555555555555555555555
    url(r'^companyapplyfifth/$', views.companyapplyfifth, name='comfifth'),
    #公司申请提交中66666666666666666666666666
    url(r'^authsuccess/$',views.authsuccess,name='authsuccess'),
    #公司岗位申请第一部1111111111111111111111
    # url(r'^bindstepfirst/$',views.bindstepfirst,name='bindstepfirst'),
    #公司岗位申请第二部2222222222222222222222
    # url(r'^bindstepsecond/$',views.bindstepsecond,name='bindstepsecond'),
    #公司岗位申请第三部3333333333333333333333
    # url(r'^bindstepthird/$',views.bindstepthird,name='bindstepthird'),
    #岗位收藏页面
    url(r'^collections/(?P<u_id>\d+)/',views.collections,name='collections'),
    url(r'^collections1/(?P<u_id>\d+)/', views.collections1, name='collections1'),
    url(r'^collections/(?P<u_id>\d+)/', views.collections2, name='collections2'),

    #简历查看情况等一系列页面，招收新职位除外
    url(r'^canInter/$',views.canInter,name='caninter'),
    #公司发布新的岗位
    url(r'^jobnewapply/$',views.createnewjob,name='createnewjob'),
    #公司协议
    url(r'^protocol/$',views.protocol,name='protocol'),
    # url(r'')
    url(r'^refuse/$',views.haveRefuseResumes,name='refuse'),
    url(r'^notice/$',views.haveNoticeResumes,name='notice'),
    url(r'^interview/$',views.canInter,name='interview')

]

Lagouwh/Lagouwh/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/',include('App.urls',namespace='app')),
]

Lagouwh/templates/about.html
{% extends 'base.html' %}
{% block middle %}
    <div id="container">

        <div class="content_mid">
            <dl class="c_section c_section_mid">
                <dt>
                    <h2><em></em>联系我们</h2>
                </dt>
                <dd class="aboutus">
                    <img alt="拉勾网团队" src="/static/images/aboutus.jpg" width="186" height="186"/>
                    <div>
                        <span>拉勾网（隶属于北京拉勾网络技术有限公司）是专注互联网职业机会的招聘网站，以众多优质互联网资源为依托，发布圈内招聘信息，为求职者提供人性化、个性化、专业化的信息服务，以让优质人才和优秀企业及时相遇为己任。</span>
                        <span>我们是一个热爱互联网的年轻团队，我们用责任来做这件事情，致力于打造最专业的互联网招聘平台。</span>
                    </div>
                    <ul class="reset contact_box">
                        <li class="cli1">
                            <p>商务合作：</p>
                            邮箱：<a href="mailto:pqzhao@lagou.com">pqzhao@lagou.com</a>

                            地址：北京市海淀区海淀西大街70号
                        </li>
                        <li class="cli2">
                            增值服务：<br/>
                            邮箱：<a href="mailto:bill@lagou.com">bill@lagou.com</a><br/>
                        </li>
                        <li class="cli3">
                            客服邮箱：<a href="mailto:vivi@lagou.com">vivi@lagou.com</a><br/>
                            电话：010-57286997(9:30-21:00)<br/>
                            <span>
								<!-- WPA Button Begin -->
								<script charset="utf-8" type="text/javascript"
                                        src="http://wpa.b.qq.com/cgi/wpa.php?key=XzgwMDA1NjM3OV8xNDUzODBfODAwMDU2Mzc5Xw"></script>
                                <!-- WPA Button End -->
							</span>
                        </li>
                    </ul>
                </dd>
            </dl>
        </div>
        <div class="clear"></div>
        <input type="hidden" id="resubmitToken" value=""/>
        <a id="backtop" title="回到顶部" rel="nofollow"></a>
    </div><!-- end #container -->
    </div><!-- end #body -->
{% endblock middle %}

Lagouwh/templates/bindStep2.html
{% extends 'base.html' %}
{% block middle %}
    <div id="container">
        <style>.ui-autocomplete {
            max-height: 160px;
            overflow-y: scroll;
        }</style>
        <div class="content_mid">
            <!--form-->
            <dl class="c_section c_section_service">
                <dt>
                    <h2><em></em>开通招聘服务</h2>
                </dt>
                <dd>
                    <div class="os_step_2"></div>
                    <form class="corp_form" id="companyNameForm">
                        <input type="hidden" value="3a9b3124ee0a4adca922f2c9756d1ac1" id="resubmitToken">
                        <h3><em class="redstar">*</em>公司全称 <span class="explain">（请输入与公司营业执照一致的公司全称，审核通过后不可更改）</span>
                        </h3>
                        <span role="status" aria-live="polite" class="ui-helper-hidden-accessible">测试公司</span><input
                            type="text" value="" placeholder="请输入与公司营业执照一致的公司全称" name="companyName" id="companyName"
                            class="valid ui-autocomplete-input" autocomplete="off">
                        <input type="submit" value="提 交" id="bindSubmit">
                        <a class="goback" href="h/corpCenter/bindStep1.html?update=1">返回修改邮箱地址</a>
                    </form>
                    <div class="contactus">如有问题，请致电：010-57286997或写信给：<a href="mailto:vivi@lagou.com">vivi@lagou.com</a>，我们会尽快为你解决。
                    </div>
                </dd>
            </dl>
        </div>
        <div class="dn" id="loadingDiv" style="display: none;"><img width="32" height="32"
                                                                    src="style/images/ajax-loader.gif"></div>
        <script src="style/js/services.min.js" type="text/javascript"></script>
        <div class="clear"></div>
        <input type="hidden" value="3a9b3124ee0a4adca922f2c9756d1ac1" id="resubmitToken">
        <a rel="nofollow" title="回到顶部" id="backtop"></a>
    </div><!-- end #container -->
{% endblock middle %}

Lagouwh/templates/bindstep1.html
{% extends 'base.html' %}
{% block middle %}
    <div id="container">
        <div class="content_mid">
            <!--form-->
            <dl class="c_section c_section_service">
                <dt>
                    <h2><em></em>开通招聘服务</h2>
                </dt>
                <dd>
                    <div class="os_step_1"></div>
                    <form class="corp_form" id="bindForm">
                        <input type="hidden" value="a517d13d23f5432eab682688151c3673" id="resubmitToken">
                        <h3><em class="redstar">*</em>联系电话 <span>（请填写真实有效的电话号码，方便系统校验使用）</span></h3>
                        <input type="text" value="" placeholder="请输入你的手机号码或座机号码" maxlength="49" name="tel" id="tel">
                        <h3><em class="redstar">*</em>接收简历邮箱 <span>（该邮箱为公司邮箱，审核通过后不可更改）</span></h3>
                        <input type="text" value="" placeholder="请输入你的公司邮箱作为接收简历邮箱" name="email" id="email">
                        <span id="beError" style="display:none;" class="error"></span>
                        <input type="submit" value="下一步" id="bindSubmit">
                    </form>
                    <div class="contactus">
                        <table>
                            <tbody>
                            <tr>
                                <td colspan="2">常见问题：</td>
                            </tr>
                            <tr>
                                <td valign="top">问：</td>
                                <td>填写个人邮箱可以么？</td>
                            </tr>
                            <tr>
                                <td valign="top">答：</td>
                                <td>
                                    不可以。为了保证每个职位的真实性，拉勾网严格要求招聘方必须提供公司邮箱。（公司邮箱是指以你的公司网址为后缀的免费公司邮箱，例如拉勾网的公司邮箱后缀是@lagou.com）即使是初创公司也必须提供公司邮箱才允许开通招聘。
                                </td>
                            </tr>
                            <tr>
                                <td valign="top">问：</td>
                                <td>公司没有公司邮箱怎么办？</td>
                            </tr>
                            <tr>
                                <td valign="top">答：</td>
                                <td>拉勾网推荐使用免费、稳定的腾讯企业邮箱（网址：<a href="http://exmail.qq.com">http://exmail.qq.com</a>），根据邮箱申请指南进行操作，很快就可以拥有以你的公司网址为后缀的免费公司邮箱。
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2"><br>如有其它问题，请发送问题到<a href="mailto:vivi@lagou.com">vivi@lagou.com</a>，我们会尽快为你解决。
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </dd>
            </dl>
        </div>

        <script src="style/js/services.min.js" type="text/javascript"></script>
        <div class="clear"></div>
        <input type="hidden" value="a517d13d23f5432eab682688151c3673" id="resubmitToken">
        <a rel="nofollow" title="回到顶部" id="backtop"></a>
    </div><!-- end #container -->
{% endblock middle %}

Lagouwh/templates/companyapplyfourth.html
{% extends 'base.html' %}
{% block middle %}
    <div id="container">

        <div class="content_mid">
            <dl class="c_section c_section_mid">
                <dt>
                    <h2><em></em>填写公司信息</h2>
                    <a class="c_addjob" href="create.html"></a>
                </dt>
                <dd>
                    <div class="c_text">目标明确、前途光明的产品是吸引求职者的制胜法宝哦！</div>
                    <img width="668" height="56" class="c_steps" alt="第四步" src="/static/images/step4.png">

                    <form method="post" action="{% url 'app:comfifth' %}" id="productForm">
                        {% csrf_token %}
                        <input type="hidden" value="8f79f658e49846ae89d90a3f1590f12e" name="resubmitToken">
                        <input type="hidden" id="companyId" name="companyId" value="25927">
                        <div id="productDiv">
                            <div class="formWrapper">

                                <h3>产品名称</h3>
                                <input type="text" placeholder="请输入产品名称" name="p_name" id="name0">

                                <h3>产品地址</h3>
                                <input type="text" placeholder="请输入产品主页URL或产品下载地址" name="p_web"
                                       id="address0">

                                <h3>产品简介</h3>
                                <textarea placeholder="请简短描述该产品定位、产品特色、用户群体等" maxlength="1000"
                                          name="p_intr" id="description0"></textarea>
                                <div class="word_count">你还可以输入 <span>500</span> 字</div>
                            </div>
                        </div>
                        <a id="addMember" class="add_member" href="javascript:void(0)"></a>
                        <div class="clear"></div>
                        <input type="submit" value="保存，下一步" id="step4Submit" class="btn_big fr">
{#                        <a class="btn_cancel fr" href="{">跳过</a>#}
                    </form>
                </dd>
            </dl>
        </div>

        <script src="style/js/step4.min.js" type="text/javascript"></script>
        <div class="clear"></div>
        <input type="hidden" value="8f79f658e49846ae89d90a3f1590f12e" id="resubmitToken">
        <a rel="nofollow" title="回到顶部" id="backtop" style="display: none;"></a>
    </div><!-- end #container -->
    </div><!-- end #body -->
{% endblock %}

Lagouwh/templates/companyapplythird.html
{% extends 'base.html' %}
{% block middle %}
    <div id="container">

        <div class="content_mid">
            <dl class="c_section c_section_mid">
                <dt>
                    <h2><em></em>填写公司信息</h2>
                    <a class="c_addjob" href="create.html"></a>
                </dt>
                <dd>
                    <div class="c_text">展示强劲的创始团队，让求职者跟随而来吧！</div>
                    <img width="668" height="56" class="c_steps" alt="第三步" src="/static/images/step3.png">

                    <form method="post" action="{% url 'app:comfourth' %}" id="memberForm">
                        {% csrf_token %}
                        <input type="hidden" value="52346c62232045a8ab1d45cb3e0540b7" name="resubmitToken">
                        <input type="hidden" id="companyId" name="companyId" value="25927">
                        <div id="memberDiv">
                            <div class="formWrapper">
{#                                <input type="hidden" value="25927" name="leaderInfos[0].companyId">#}
{#                                <div class="new_portrait">#}
{#                                    <div class="portrait_upload" id="portraitNo0">#}
{#                                        <span>上传创始人头像</span>#}
{#                                    </div>#}
{#                                    <div class="portraitShow dn" id="portraitShow0">#}
{#                                        <img width="120" height="120" src="">#}
{#                                        <span>更换头像</span>#}
{#                                    </div>#}
{#                                    <input type="file" value="" title="支持jpg、jpeg、gif、png格式，文件小于5M"#}
{#                                           onchange="img_check(this,'http://www.lagou.com/c/upload.json',120,120,5,'myfiles0','myfiles0_error','portraitNo0','portraitShow0','type0','leaderInfos0');"#}
{#                                           name="myfiles" id="myfiles0" class="myfiles">#}
{#                                    <input type="hidden" value="7" name="type" id="type0">#}
{#                                    <input type="hidden" name="leaderInfos[0].photo" id="leaderInfos0">#}
{#                                    <em>#}
{#                                        尺寸：120*120px <br>#}
{#                                        大小：小于5M#}
{#                                    </em>#}
{#                                    <span style="display:none;" id="myfiles0_error" class="error"></span>#}
{#                                </div>#}


                                <h3>创始人姓名</h3>
                                <input type="text" placeholder="请输入创始人姓名" name="f_name" id="name0"
                                       class="s_input1 valid">

                                <h3>当前职位</h3>
                                <input type="text" placeholder="请输入当前职位，如：创始人兼CEO" name="f_position"
                                       id="position0" class="s_input1 valid">

{#                                <h3>新浪微博</h3>#}
{#                                <input type="text" placeholder="请输入创始人新浪微博地址" name="leaderInfos[0].weibo" id="weibo0">#}

                                <h3>创始人简介</h3>
                                <textarea placeholder="请输入该创始人的个人履历等，建议按照时间倒序分条展示" maxlength="1000"
                                          name="f_introduction" id="description0"></textarea>
                                <div class="word_count">你还可以输入 <span>500</span> 字</div>
                            </div>
                        </div>
{#                        <a id="addMember" class="add_member" href="javascript:void(0)"><i></i>继续添加创始团队</a>#}
                        <div class="clear"></div>
                        <input type="submit" value="保存，下一步" id="step3Submit" class="btn_big fr">
{#                        <a class="btn_cancel fr" href="{% url 'app:comfourth' %}">跳过</a>#}
                    </form>
                </dd>
            </dl>
        </div>


        <script src="/static/js/step3.min.js" type="text/javascript"></script>
        <div class="clear"></div>
        <input type="hidden" value="52346c62232045a8ab1d45cb3e0540b7" id="resubmitToken">
        <a rel="nofollow" title="回到顶部" id="backtop" style="display: inline;"></a>
    </div><!-- end #container -->
{#    </div><!-- end #body -->#}
    <!--  -->
{% endblock %}

Lagouwh/templates/haveRefuseResumes.html
{% extends 'base.html' %}
{% block middle %}
    <div id="noticeTip">
        <span class="bot"></span>
        <span class="top"></span>
        <a target="_blank" href="delivery.html"><strong>1</strong>条新投递反馈</a>
        <a class="closeNT" href=""></a>
    </div>
    <!-- end #header -->
    <div id="container">
        <div class="sidebar">
            <a class="btn_create" href="create.html">发布新职位</a>
            <dl class="company_center_aside">
                <dt>我收到的简历</dt>
                <dd>
                    <a href="{% url 'app:interview' %}">待处理简历</a>
                </dd>
                <dd>
                    <a href="{% url 'app:notice' %}">已通知面试简历</a>
                </dd>
                <dd class="current">
                    <a href="{% url 'app:refuse' %}">不合适简历</a>
                </dd>
            </dl>
        </div><!-- end .sidebar -->
        <div class="content">
            <dl class="company_center_content">
                <dt>
                    <h1>
                        <em></em>
                        不合适简历 <span>（共1份）</span></h1>
                </dt>
                <dd>
                    <form action="haveRefuseResumes.html" method="get" id="filterForm">
                        <div class="filter_actions ">
                            <label class="checkbox">
                                <input type="checkbox">
                                <i></i>
                            </label>
                            <span>全选</span>
                            <a id="resumeDelAll" href="javascript:;">删除</a>
                            <div id="filter_btn">筛选简历 <em></em></div>
                        </div><!-- end .filter_actions -->
                        <div class="filter_options  dn ">
                            <dl>
                                <dt>简历状态：</dt>
                                <dd>
                                    <a rel="-1" class="current" href="javascript:;">不限</a>
                                    <a rel="1" href="javascript:;">未阅读</a>
                                    <a rel="2" href="javascript:;">已阅读</a>
                                    <a rel="3" href="javascript:;">已转发</a>
                                    <input type="hidden" value="-1" name="resumeStatus">
                                </dd>
                            </dl>
                            <dl>
                                <dt>简历形式：</dt>
                                <dd>
                                    <a rel="-1" class="current" href="javascript:;">不限</a>
                                    <a rel="0" href="javascript:;">附件简历</a>
                                    <a rel="1" href="javascript:;">在线简历</a>
                                    <input type="hidden" value="-1" name="resumeType">
                                </dd>
                            </dl>
                            <dl>
                                <dt>工作经验：</dt>
                                <dd>
                                    <a rel="-1" class="current" href="javascript:;">不限</a>
                                    <a rel="1" href="javascript:;">应届毕业生</a>
                                    <a rel="2" href="javascript:;">一年以下</a>
                                    <a rel="3" href="javascript:;">1-3年</a>
                                    <a rel="4" href="javascript:;">3-5年</a>
                                    <a rel="5" href="javascript:;">5-10年</a>
                                    <a rel="6" href="javascript:;">10年以上</a>
                                    <input type="hidden" value="-1" name="workExp">
                                </dd>
                            </dl>
                            <dl>
                                <dt>最低学历：</dt>
                                <dd>
                                    <a rel="-1" class="current" href="javascript:;">不限</a>
                                    <a rel="1" href="javascript:;">大专及以上</a>
                                    <a rel="2" href="javascript:;">本科及以上</a>
                                    <a rel="3" href="javascript:;">硕士及以上</a>
                                    <a rel="4" href="javascript:;">博士及以上</a>
                                    <input type="hidden" value="-1" name="eduExp">
                                </dd>
                            </dl>
                            <input type="hidden" value="0" name="filterStatus" id="filterStatus">
                            <input type="hidden" value="" name="positionId" id="positionId">
                        </div><!-- end .filter_options -->
                        <ul class="reset resumeLists">
                        </ul><!-- end .resumeLists -->
                    </form>
                </dd>
            </dl><!-- end .company_center_content -->
        </div><!-- end .content -->
                            {% for i in resume %}
                            <li data-id="{{ i.owner.id }}" class="onlineResume">
                                <label class="checkbox">
                                    <input type="checkbox">
                                    <i></i>
                                </label>
                                <div class="resumeShow">
                                    <a title="预览在线简历" target="_blank" class="resumeImg"
                                       href="resumeView.html?deliverId=1686182">
                                        <img src="/static/images/default_headpic.png">
                                    </a>
                                    <div class="resumeIntro">
                                        <h3 class="unread">
                                            <a target="_blank" title="预览jason的简历"
                                               href="">
                                                {{ i.owner.username }}的简历
                                            </a>
                                            <em></em>
                                        </h3>
                                        <span class="fr">{{ i.resume.owner.u_regtime }}</span>
                                        <div>
                                            {{ i.resume }} / {{ i.owner.sex }} / {{ i.owner.degree }} / {{ i.owner.exper }} / {{ i.owner.u_address }} <br>
                                            {{ i.resume.myjob }}|{{ i.owner.degree }}·{{ i.owner.collage }}
                                        </div>
                                        <div class="jdpublisher">
				                                        <span>
				                                        	应聘职位：<a title="{{ i.resume.myjob  }}" target="_blank"
                                                                    href="http://www.lagou.com/jobs/149594.html">{{ i.resume.myjob }}</a>
				                                       						                                        </span>
                                        </div>
                                    </div>
                                    <div class="links">
                                        <a data-resumename="jason的简历" data-positionname="随便写" data-deliverid="1686182"
                                           data-positionid="149594" data-resumekey="1ccca806e13637f7b1a4560f80f08057"
                                           data-forwardcount="1" class="resume_forward" href="javascript:void(0)">
                                            转发
                                            <span>(1人)</span>
                                        </a>
                                        <a class="resume_del" href="javascript:void(0)">删除</a>
                                    </div>
                                </div>
                                 <div class="contactInfo">
                                    <span class="c9">电话：</span>{{ i.owner.phonenum }} &nbsp;&nbsp;&nbsp;
                                    <span class="c9">邮箱：</span><a>{{ i.owner.email }}</a>
                                </div>
                            </li>
                            {% endfor %}

{% endblock middle %}